rosepearson/GeoFabrics

src/geofabrics/geometry.py
src/geofabrics/lidar.py
src/geofabrics/processor.py

Hi @rosepearson 
Here's a few updates found after checking out the code. Couldn't run the examples, nor the tests. I tried `pip install .` but it failed due to PDAL. Tried installing the lib-something-pdal on Ubuntu, didn't fix. Tried to create a Conda environment, but it was taking ages and in the end conda crashed :sweat_smile: 
So just read some parts of the code, ran a quick IDE analysis, and prepared this PR fixing some of the IDE warnings.
Cheers
Bruno

Typo, duplicated dict key, and write to log

---

.github/workflows/update_pages.yml
README.md
docs/Makefile
docs/conf.py
docs/index.rst
docs/make.bat
docs/requirements.txt
setup.py
src/geofabrics/__init__.py
src/geofabrics/dem.py
src/geofabrics/geometry.py
src/geofabrics/processor.py
src/main.py

Setup Sphinx documentation:
I've done some more reading and come to the following conclusions:
1. Merge the sphinx source documentation into main - the following GH actions will build this and push the artefacts to the gh-pages branch
2. Use GH actions to test building of Sphinx documentation https://github.com/marketplace/actions/sphinx-build
3. Use GH actions to deploy Sphinx documentation to pages https://github.com/marketplace/actions/sphinx-pages
Full example: https://github.com/marketplace/actions/sphinx-to-github-pages

45 documentation sphinx

---

.github/workflows/update_pages.yml
src/benchmarking.py
src/geofabrics/processor.py
src/main.py

Added script for benchmarking performance of geofabrics for a dataset at a range of chunk-sizes and number-of-CPU-cores:

52 benchmarking

---

src/geofabrics/__init__.py
src/geofabrics/dem.py
src/geofabrics/processor.py
tests/test_processor_local_files/instruction.json
tests/test_processor_local_files_limited_offshore_res/instruction.json
tests/test_processor_local_files_offshore_after/instruction.json
tests/test_processor_remote_all_westport/instruction.json
tests/test_processor_remote_all_westport_ground_only/instruction.json
tests/test_processor_remote_tiles_wellington/instruction.json
tests/test_processor_remote_tiles_wellington_ground_only/instruction.json
tests/test_processor_remote_tiles_westport/instruction.json
tests/test_processor_remote_tiles_westport_ground_only/instruction.json

57 other classifications

---

src/geofabrics/__init__.py
src/geofabrics/dem.py
src/geofabrics/processor.py
tests/test_processor_remote_tiles_wellington_elevation_filter/__init__.py
tests/test_processor_remote_tiles_wellington_elevation_filter/data/benchmark_dem.nc
tests/test_processor_remote_tiles_wellington_elevation_filter/instruction.json
tests/test_processor_remote_tiles_wellington_elevation_filter/test_processor_remote_tiles_wellington_elevation_filter.py

65 add support for a valid range of lidar point elevations

---

.github/workflows/autoblack.yml
docs/conf.py
setup.py
src/benchmarking.py
src/geofabrics/bathymetry_estimation.py
src/geofabrics/dem.py
src/geofabrics/geometry.py
src/geofabrics/processor.py
src/geofabrics/version.py
src/main.py
tests/test_processor_local_files/test_processor_local_files.py
tests/test_processor_local_files_limited_offshore_res/test_processor_local_files_limited_offshore_res.py
tests/test_processor_local_files_offshore_after/test_processor_local_files_offshore_after.py
tests/test_processor_remote_all_westport/test_processor_remote_all_westport.py
tests/test_processor_remote_all_westport_ground_only/test_processor_remote_all_westport_ground_only.py
tests/test_processor_remote_tiles_wellington/test_processor_remote_tiles_wellington.py
tests/test_processor_remote_tiles_wellington_elevation_filter/test_processor_remote_tiles_wellington_elevation_filter.py
tests/test_processor_remote_tiles_wellington_ground_only/test_processor_remote_tiles_wellington_ground_only.py
tests/test_processor_remote_tiles_westport/test_processor_remote_tiles_westport.py
tests/test_processor_remote_tiles_westport_ground_only/test_processor_remote_tiles_westport_ground_only.py
tests/test_river_bathymetry_wellington/test_river_bathymetry_wellington.py

Move to using the Black formatter and fix all warnings:

47 setup a formatter

---

README.md
pyproject.toml
setup.py
src/geofabrics/version.py

This PR just brings the code base in line with the PyPI package. Note that this package is broken and will be addressed in the followup issue https://github.com/rosepearson/GeoFabrics/issues/81:

Migration to pyproject.toml.

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/processor.py
src/geofabrics/version.py
tests/test_river_bathymetry_wellington/test_river_bathymetry_wellington.py

Remove the python-pdal dependency that does not exist on PyPI and also remove errors warnings where possible:

81 bugfix - PyPI dependencies

---

pyproject.toml
src/geofabrics/geometry.py
src/geofabrics/version.py

85-Geopandas geoms address warning

---

src/main.py

Print out log files separately for each processor class and int he subfolder:

97 update logging for main

---

environment_linux.yml
environment_windows.yml
src/geofabrics/processor.py
src/geofabrics/version.py
tests/test_all_bathymetry_into_dem_wellington/instruction.json
tests/test_all_bathymetry_into_dem_wellington/test_all_bathymetry_into_dem_wellington.py
tests/test_all_bathymetry_into_dem_wellington_with_roughness/instruction.json
tests/test_all_bathymetry_into_dem_wellington_with_roughness/test_all_bathymetry_into_dem_wellington_with_roughness.py
tests/test_processor_remote_all_westport/data/benchmark_dem.nc
tests/test_processor_remote_all_westport/instruction.json
tests/test_processor_remote_all_westport/test_processor_remote_all_westport.py
tests/test_processor_remote_all_westport_ground_only/instruction.json
tests/test_processor_remote_all_westport_ground_only/test_processor_remote_all_westport_ground_only.py
tests/test_processor_remote_tiles_wellington/instruction.json
tests/test_processor_remote_tiles_wellington_elevation_filter/instruction.json
tests/test_processor_remote_tiles_wellington_ground_only/instruction.json
tests/test_processor_remote_tiles_westport/instruction.json
tests/test_processor_remote_tiles_westport_ground_only/instruction.json
tests/test_river_bathymetry_osm_wellington/instruction.json
tests/test_river_bathymetry_osm_wellington/test_river_bathymetry_osm_wellington.py
tests/test_river_bathymetry_wellington/instruction.json
tests/test_river_bathymetry_wellington/test_river_bathymetry_wellington.py
tests/test_waterways_bathymetry_wellington/instruction.json
tests/test_waterways_bathymetry_wellington/test_waterways_bathymetry_wellington.py

* Support downloading reference DEMs using Geoapis new raster module
* Update the environments to conda for geoapis
* Add a test

Support raster downloads

---

pyproject.toml

Bumpy pyproject.toml to match version.py:

122 bugfix bump verion number in the pyprojecttoml

---

pyproject.toml
src/geofabrics/bathymetry_estimation.py
src/geofabrics/processor.py

~~- [ ] Update tests~~
~~- [ ] Update / create new tests~~
~~- [ ] Ensure these tests have the expected behavour~~
~~- [ ] Update documentation~~
~~- [ ] Doc strings~~
~~- [ ] Wiki~~

120 bugfix assert messages over multiple lines are not printing correctly due to string formatting errors

---

pyproject.toml
src/geofabrics/geometry.py
src/geofabrics/version.py

Change logic for getting the ocean contour to interpolate to when generating an ocean fan to make more robust:

119 bugfix ocean bathymetry

---

pyproject.toml
setup.cfg
setup.py
src/__main__.py
src/geofabrics.py
src/geofabrics/runner.py

Create a CLI and also a module for calling the package.
@LukeParky keen for some input here about what you think is the best way to proceed. Options include
a. Keep a script in src and create a single "cli_run_from_file"
b. Push some of the contents of geofarbics.py (now __main__.py) into the geofabrics folder - maybe __init__,py
* Create multiple cli files one for each functionality - like running from dict or running from path

name main.py and made so there are some module entry points

---

pyproject.toml
setup.cfg
setup.py

Fix entry point reference. This time tested with build locally for creating a PyPI distribution:

Fix reference to entry point

---

pyproject.toml
src/geofabrics/processor.py
src/geofabrics/version.py

146 download all raster in overall catchment for waterways

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/version.py
tests/test_multiple_lidar_ground_only_roughness/__init__.py
tests/test_multiple_lidar_ground_only_roughness/data/benchmark.nc
tests/test_multiple_lidar_ground_only_roughness/instruction.json
tests/test_multiple_lidar_ground_only_roughness/test_multiple_lidar_ground_only_roughness.py

Added test for roughness from multiple LiDAR and also fixed the dem module to correctly combine roughness layers from multiple LiDAR datasets:

149 bug fix roughness + add test

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/version.py

1. Replace assert with warning for exceeding the 10,000 pt RBF limit
2. Only perform a merge if there are multiple DEMs/Zo's

151 make 10000 rbf limit soft ie warning not error

---

pyproject.toml
src/geofabrics/bathymetry_estimation.py
src/geofabrics/dem.py
src/geofabrics/geometry.py
src/geofabrics/processor.py
src/geofabrics/runner.py
src/geofabrics/version.py

155 cyclone gabriel easy fixes

---

README.md
examples/case_study_2/4m_no_waterways.json
examples/case_study_2/4m_with_waterways.json
src/geofabrics/dem.py

175 fix examples

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/processor.py
src/geofabrics/version.py

Improve robustness in case of now tunnels/closed waterways in an area:

Deal with no tunnel waterways

---

pyproject.toml
src/geofabrics/processor.py
src/geofabrics/version.py
tests/test_dem_generation_wellington_1/test_dem_generation_wellington_1.py
tests/test_dem_generation_wellington_2/test_dem_generation_wellington_2.py
tests/test_dem_generation_westport_1/test_dem_generation_westport_1.py
tests/test_dem_generation_westport_2/test_dem_generation_westport_2.py
tests/test_dem_generation_westport_3/test_dem_generation_westport_3.py
tests/test_dem_generation_westport_4/test_dem_generation_westport_4.py

* New downloads folder datapath
* Nest raster, lidar and vector in downloads datapath
* Nest all LiDAR data under a lidar folder

Nest downloads

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/processor.py
src/geofabrics/version.py

153- Cylone Gabrielle related fixes

---

.github/workflows/contributors.yml
pyproject.toml
src/geofabrics/version.py

Just bump version and update the contributor list action:

Bump version and try fix collaborator list update

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/processor.py
src/geofabrics/runner.py
src/geofabrics/version.py
tests/test_many_stages_local/instruction.json
tests/test_many_stages_local/test_many_stages_local.py
tests/test_many_stages_multiple_1/instruction.json
tests/test_many_stages_multiple_1/test_many_stages_multiple_1.py
tests/test_many_stages_wellington/instruction.json
tests/test_many_stages_wellington/test_many_stages_wellington.py
tests/test_many_stages_westport/instruction.json
tests/test_many_stages_westport/test_many_stages_westport.py

* Fix bug related to dask performance changes
* Simplify instruction files

Errors related to dask performance changes

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/version.py
tests/test_dem_generation_local_1/data/benchmark_dem.nc
tests/test_dem_generation_local_3/data/benchmark_dem.nc
tests/test_dem_generation_westport_4/instruction.json
tests/test_many_stages_local/data/benchmark_geofabric.nc

Remove coarse DEMs in the ocean just outside the foreshore:

196 fix coarse dem in ocean

---

examples/case_study_1/8m_conceptual_multivariate.json
examples/case_study_1/8m_interpolated_river.json
examples/case_study_1/8m_unconditioned.json
examples/case_study_1/8m_uniform_flow.json
examples/case_study_2/4m_no_waterways.json
examples/case_study_2/4m_with_waterways.json
pyproject.toml
src/geofabrics/processor.py
src/geofabrics/version.py
tests/test_many_stages_wellington/instruction.json
tests/test_waterways_estimation_wellington/instruction.json

Update the examples

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/version.py

Also fixed incorrect call to logging.info

Release 1.0.0

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/geometry.py
src/geofabrics/processor.py
src/geofabrics/version.py
tests/test_many_stages_multiple_2/instruction.json

Two changes: 1. multiple drop offshore LiDAR selections, 2. be robust to areas with no waterways:

209 multiple lidar datasets multiple drop offshore lidar selection

---

README.md
pyproject.toml
src/geofabrics/dem.py
src/geofabrics/geometry.py
src/geofabrics/processor.py
src/geofabrics/version.py
tests/test_many_stages_multiple_1/data/benchmark.nc
tests/test_many_stages_multiple_1/instruction.json
tests/test_many_stages_multiple_2/data/benchmark.nc
tests/test_many_stages_multiple_2/instruction.json
tests/test_many_stages_wellington/instruction.json

Update roughness - pull out parameters, use OSM to set select defaults:

78 roughness length followup

---

.github/workflows/contributors.yml
pyproject.toml
src/geofabrics/dem.py
src/geofabrics/processor.py
src/geofabrics/version.py
tests/test_many_stages_multiple_2/data/benchmark.nc
tests/test_many_stages_multiple_2/instruction.json

Support NaN for waterways, minimum or maximum roughness default values:

214 roughness update defaults

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/version.py

* Robust to when no LiDAR datasets are specified
* Try identify cause of 'no_values_mask' error

220 - bugfixes - saving temp files

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/processor.py
src/geofabrics/runner.py
src/geofabrics/version.py
tests/test_many_stages_multiple_1/data/benchmark.nc
tests/test_many_stages_multiple_2/data/benchmark.nc

* Minimise clipping through use of masks
* no_values_mask as a property
* use the RawDem save/load functions.
* Consolidate the save/load functions back under the LidarBase class
* Cleanup logging - output to two locations

229 roughness stage dask optimisations

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/geometry.py
src/geofabrics/processor.py
src/geofabrics/version.py

Address TB found during nationwide run:

Ensure compressed and uncompresse LiDAR files are read in

---

environment_linux.yml
pyproject.toml
src/geofabrics/dem.py
src/geofabrics/processor.py
src/geofabrics/runner.py
src/geofabrics/version.py

Fix last issues with logging to at least get some outputs including run time:

237 fix logging

---

src/geofabrics/processor.py

tidy up the saving and cleaning of temporarily cached files

---

.github/workflows/tests.yml
environment.yml
environment_CI.yml
pyproject.toml
src/geofabrics/version.py
tests/test_add_patches_ngaruroro/test_case.py
tests/test_dem_generation_local_1/test_case.py
tests/test_dem_generation_local_2/test_case.py
tests/test_dem_generation_local_3/test_case.py
tests/test_dem_generation_multiple/test_case.py
tests/test_dem_generation_waikanae_1/test_case.py
tests/test_dem_generation_waikanae_2/test_case.py
tests/test_dem_generation_westport_1/test_case.py
tests/test_dem_generation_westport_2/test_case.py
tests/test_dem_generation_westport_3/test_case.py
tests/test_dem_generation_westport_4/test_case.py
tests/test_many_stages_local/test_case.py
tests/test_many_stages_multiple_1/test_case.py
tests/test_many_stages_multiple_2/test.py
tests/test_many_stages_waikanae/test_case.py
tests/test_many_stages_westport/test_case.py
tests/test_riverbed_estimation_waikanae_1/test_case.py
tests/test_riverbed_estimation_waikanae_2/test_case.py
tests/test_riverbed_interpolated_waikanae/test_case.py
tests/test_riverbed_interpolated_waitara/test_case.py
tests/test_stopbanks_waikanae/test_case.py
tests/test_waterways_estimation_waikanae/test_case.py

* Update pyproject.toml
* Update tests to test installed package
* Pull broken PyPI version 1.1.14-18

258 bugfix package broken import geofabrics error

---

pyproject.toml
src/geofabrics/dem.py
src/geofabrics/geometry.py
src/geofabrics/processor.py
src/geofabrics/version.py
tests/test_many_stages_westport/data/benchmark.nc
tests/test_stopbanks_waikanae/data/benchmark.nc
tests/test_stopbanks_waikanae/instruction.json

* Fix roughness interpolation
* Fix bug in ElevationPoints to clip polygons
* Investigate stopbank/waterways ordering - leave as is for now

271 bugfix   min value roughness where interpolated
